# Generated by Django 6.0.3 on 2026-04-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
